### PR TITLE
Fix result changes with DB updates

### PR DESCRIPTION
**Pull request by iyangar**

### CODE REVIEW

**Review by aravind-ebi — COMMENTED** [review]
Looks good to me, I'm not sure which part was causing the error. I've mentioned this to Dylan as well, maybe he could also approve of this?

**Comment by tskir** [comment]
@aravind-ebi Here's info from Selva. He told me you should be able to understand this:

----

yeah it looks good , only concern is `getGaitAnalysisInputAmpLoad52.json` it should have used getGaitAnalysisInput.json but then i figured out for the dataset it gives error if "ID" is LT "ZZZZ"  , ideally the ID filed should contain string less than ZZZZZ

the ped contains wrong id in gait machine thats why

in database SAMPLES_GWAS_HOORN_DCS_MDV2 ID is

```
30003
30007
30021
30032
30034
30037
30040
30046
30051
30052
```

but in ped

`root@ampt2d-gait:/srv/t2d-studies-plain# awk '{ print $42 }' AMPLOAD_52.ped | head -n 5`

```
ID
30003_30003
30007_30007
30021_30021
30032_30032
```

he [Sreenidhi] should have checked this , instead creating seperate input for the gait test

**Comment by tskir** [comment]
Additional comment from Selva—

----

but i guess he doesnt know restart docker application , once hte file is done you need to put in particualr path and restart the application in docker

**Comment by aravind-ebi** [comment]
Yes, I understand the issue now. Okay, so there's one of two things that can be done for this. 

1. The ID in the database can be changed to be *Sample_ID_SampleID* instead of just *Sample_ID* to match with the currently existing ped file on the gait machine.
2. The ped file must be changed to just *Sample_ID* and then pushed to the gait machine again to replace the old file.

I think 2 would be preferable as it would match up with all the other datasets/sample_ids but this would require restarting docker as Selva mentioned. I can change the file and push it to gait if necessary.

**Pull request merged**
